import { GridColDef } from "@mui/x-data-grid";

export const columns: GridColDef[] = [
    {
      field: "id",
      headerName: "ID",
      headerClassName: "columnClass",
      width: 200,
      editable: false,
      hide: true,
      filterable: false,
    },
    {
      field: "_name",
      headerName: "Nombre",
      headerClassName: "columnClass",
      width: 200,
      editable: false,
      hideable: false,
    },
    {
      field: "_rounds",
      headerName: "Rondas",
      headerClassName: "columnClass",
      type: "number",
      width: 100,
      editable: false,
      hideable: false,
    },
    {
      field: "_games",
      headerName: "Juegos",
      headerClassName: "columnClass",
      type: "number",
      width: 100,
      editable: false,
      hideable: false,
    },
    {
      field: "_current_players",
      headerName: "Jugadores",
      headerClassName: "columnClass",
      width: 100,
      editable: false,
      hideable: false,
    },
    {
      field: "_max_players",
      headerName: "Maximos Jugadores",
      headerClassName: "columnClass",
      width: 200,
      editable: false,
      hideable: false,
    },
    {
      field: "_min_players",
      headerName: "Minimos Jugadores",
      headerClassName: "columnClass",
      width: 200,
      editable: false,
      hideable: false,
    },
    {
      field: "_creator",
      headerName: "Creador",
      headerClassName: "columnClass",
      width: 150,
      editable: false,
      hideable: false,
    },
    {
      field: "_joined",
      headerName: "Joined",
      headerClassName: "columnClass",
      width: 150,
      editable: false,
      hide: true,
      filterable: false,
    },
    {
      field: "_private",
      headerName: "Privado",
      headerClassName: "columnClass",
      width: 100,
      editable: false,
      hideable: false,
    },
  ];